#pragma once

/* This file is generated by cbindgen 0.29.4. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "spotty_playback_annotations.h"
#pragma clang assume_nonnull begin


// Callback function type for audio control events (start/stop/clear). Called from a background
// decoder thread, so the callback must be thread-safe.
typedef void (*AudioControlCallback)(SpottyPlaybackAudioControlEvent);

// Callback function type for receiving raw PCM audio data. Audio format is 44.1 kHz, stereo,
// Float32, interleaved; the samples pointer is valid only for the callback invocation.
// Called from a background decoder thread, so the callback must be thread-safe.
//
// # Parameters
// - `samples`: Nullable pointer to interleaved f32 samples.
// - `sample_count`: Number of f32 values (frames * 2 for stereo).
typedef void (*AudioDataCallback)(SpottyNullableFloatSamples, size_t);

// Connection observation delivered as a C struct. `device_id` and `last_error` are valid only
// for the callback; Swift must copy them before returning. Null means missing; outbound empty
// strings and strings containing an interior NUL are also delivered as null fields. Flags are
// 0 or 1.
//
// `credentials_rejected` is a typed, definitive streaming-credential rejection. It takes
// precedence over generic reconnect errors; it does not revoke the independent Keymaster
// grant.
//
// `resume_pending` is set only inside a reconnect's rehydration window: the session is
// connected and activated but `spirc_ready` is deliberately still 0, and Swift should issue
// its resume-load targets through `spotty_playback_load` now. Readiness is published once a
// Playing event lands, a load reports a dead Spirc, or the window times out.
typedef struct SpottyConnectionSnapshot {
  uint64_t revision;
  uint64_t session_generation;
  uint8_t session_connected;
  uint8_t spirc_ready;
  uint8_t is_active_device;
  uint8_t resume_pending;
  uint8_t credentials_rejected;
  SpottyNullableCString device_id;
  SpottyNullableCString last_error;
} SpottyConnectionSnapshot;

// Callback function type for connection state change notifications. Receives a typed snapshot;
// the snapshot pointer and its string pointers are valid only for the callback invocation.
typedef void (*ConnectionStateCallback)(const struct SpottyConnectionSnapshot*);

// Device-list observation. `active_device_id` and `devices` are valid only for the callback.
// Swift must copy them before returning. A null `devices` pointer with count 0 is an empty list.
typedef struct SpottyDevicesSnapshot {
  uint64_t revision;
  uint64_t session_generation;
  SpottyNullableCString active_device_id;
  SpottyNullableDevicePointer devices;
  size_t device_count;
} SpottyDevicesSnapshot;

// Callback function type for Connect device-list updates. String pointers and the device
// array are valid only for the callback invocation.
typedef void (*DevicesCallback)(const struct SpottyDevicesSnapshot*);

// Playback observation. `track_uri` is valid only for the callback;
// Swift must copy it before returning. Null means missing; outbound empty strings and
// strings containing an interior NUL are also delivered as null fields. Flags are 0 or 1.
//
// `is_active_device` is the protocol active-member fact captured with this observation;
// it is independent of the arrival order of the connection callback.
//
// `track_unavailable` is set only on the local callback corresponding to a current requested
// track whose load failed. It is never set on protocol snapshots, preload failures, stale
// request events, or snapshots from an inactive device.
typedef struct SpottyPlaybackSnapshot {
  uint64_t revision;
  uint64_t session_generation;
  int64_t position_ms;
  int64_t duration_ms;
  int64_t timestamp_ms;
  uint8_t is_playing;
  uint8_t is_paused;
  uint8_t track_unavailable;
  uint8_t shuffle;
  uint8_t repeat_track;
  uint8_t repeat_context;
  uint8_t is_active_device;
  SpottyNullableCString track_uri;
} SpottyPlaybackSnapshot;

// Callback function type for playback state updates. Receives a typed snapshot; string
// pointers are valid only for the callback invocation.
typedef void (*PlaybackStateCallback)(const struct SpottyPlaybackSnapshot*);

// Queue observation. Pointers are valid only for the callback or until
// `spotty_playback_free_queue_snapshot`. Null `next_tracks`/`prev_tracks` with count 0 is an
// empty list. A missing current track is three null track fields. Outbound empty strings and
// strings containing an interior NUL are delivered as null fields.
typedef struct SpottyQueueSnapshot {
  uint64_t revision;
  uint64_t session_generation;
  SpottyNullableCString track_uri;
  SpottyNullableCString track_provider;
  SpottyNullableCString track_uid;
  SpottyNullableQueueTrackPointer next_tracks;
  size_t next_count;
  SpottyNullableQueueTrackPointer prev_tracks;
  size_t prev_count;
  SpottyNullableCString queue_revision;
  uint8_t disallow_set_queue;
  uint8_t disallow_removing_from_next_tracks;
} SpottyQueueSnapshot;

// Callback function type for queue updates. Receives a typed snapshot; strings and nested
// pointers are valid only for the callback invocation.
typedef void (*QueueCallback)(const struct SpottyQueueSnapshot*);

// One Connect metadata pair. Pointers are valid only for the callback or until
// `spotty_playback_free_queue_snapshot`. Null means missing; outbound empty strings and
// strings containing an interior NUL are also delivered as null fields.
typedef struct SpottyStringPair {
  SpottyNullableCString key;
  SpottyNullableCString value;
} SpottyStringPair;

// One restriction key with its reason list. Pointers are valid only for the callback or until
// `spotty_playback_free_queue_snapshot`. A null key or reason means that value is missing.
typedef struct SpottyRestriction {
  SpottyNullableCString key;
  SpottyNullableCStringArray reasons;
  size_t reason_count;
} SpottyRestriction;

// Unfiltered Connect queue row. String and nested pointers are valid only for the callback
// or until `spotty_playback_free_queue_snapshot`. Null means missing; outbound empty strings
// and strings containing an interior NUL are also delivered as null fields.
typedef struct SpottyProtocolQueueTrack {
  SpottyNullableCString uri;
  SpottyNullableCString uid;
  SpottyNullableCString provider;
  SpottyNullableStringPairPointer metadata;
  size_t metadata_count;
  SpottyNullableCStringArray removed;
  size_t removed_count;
  SpottyNullableCStringArray blocked;
  size_t blocked_count;
  SpottyNullableRestrictionPointer restrictions;
  size_t restriction_count;
  SpottyNullableCString album_uri;
  SpottyNullableCStringArray disallow_reasons;
  size_t disallow_reason_count;
  SpottyNullableCString artist_uri;
} SpottyProtocolQueueTrack;

// One Connect cluster member. String pointers are valid only for the callback. Null means
// missing; outbound empty strings and strings containing an interior NUL are also delivered
// as null fields.
typedef struct SpottyProtocolDevice {
  SpottyNullableCString id;
  SpottyNullableCString name;
  SpottyNullableCString device_type;
} SpottyProtocolDevice;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Adds a URI to the Connect queue.
//
// The command forwards the string to Spirc as a single Spotify URI. Track URIs are the path
// Spotty uses; this export does not resolve episodes, shows, or context URIs into a list of
// tracks.
//
// # Parameters
// - `uri`: Spotify URI (for example, "spotify:track:xxx").
SpottyPlaybackResult spotty_playback_add_to_queue(const char *uri);

// Completes the one-time streaming authorization with a token Swift has already minted:
// connects once and persists the credentials every later init connects from.
//
// Returns 0 on success, -1 on failure, -2 if the run was superseded.
//
// Swift owns the OAuth flow itself through `KeymasterAuth`; this call performs the librespot AP
// connect and persists the streaming credentials for later initialization. The same grant also
// authorizes pathfinder and spclient, so the token is minted by Swift before this call.
//
// The token must be minted with Spotify's first-party desktop client ID; a token minted with a
// user dashboard client ID is rejected by login5.
int32_t spotty_playback_authorize_streaming(const char *access_token);

// Cleans up all player state, allowing a fresh reinitialization.
// Call this before spotty_playback_init_player() when the session has disconnected.
// This clears all static state (session, player, spirc, etc.)
void spotty_playback_cleanup(void);

// Removes the cached streaming credentials.
//
// Call on logout, after the session teardown, so that the next launch cannot connect the
// account that just logged out. Removing credentials that are not there is not an error.
void spotty_playback_clear_streaming_credentials(void);

// Disconnects from Spotify Connect without preventing future reconnection.
// Use this before system sleep - the device disappears from Spotify immediately,
// but forceReconnect() can still bring it back on wake.
// Unlike shutdown(), this does NOT set SHUTTING_DOWN, so auto-reconnect still works.
// Returns 0 on success, -1 on error.
SpottyPlaybackResult spotty_playback_disconnect(void);

// Forces a reconnection to Spotify servers.
//
// Use this after system wake to ensure a fresh connection.
// Returns:
// - 0: Reconnection triggered.
// - 1: Reconnection already in progress.
// - 2: No session initialized (nothing to reconnect).
int32_t spotty_playback_force_reconnect(void);

// Frees a queue snapshot allocated by `spotty_playback_get_queue_snapshot`. Tolerates a null
// pointer.
void spotty_playback_free_queue_snapshot(SpottyNullableQueueSnapshot snapshot);

// Frees a C string allocated by this library. Tolerates a null pointer, including the result
// of an export that returned null on error.
void spotty_playback_free_string(SpottyNullableMutCString s);

// Returns the last position the Player reported, in milliseconds, or 0 if it has not reported
// one. Deliberately not interpolated: Swift owns display interpolation.
uint32_t spotty_playback_get_position_ms(void);

// The last queue the cluster described, or null if no cluster update has arrived.
//
// Cached independently of callback registration so a getter after late registration still
// recovers a tick that arrived while Swift was not listening.
//
// Replaces `/me/player/queue` and `/me/player` for Swift's bootstrap. Deliberately a snapshot
// of what was already pushed rather than a fresh request: the cluster is the only source now,
// so there is nothing newer to fetch, and a caller that gets null has genuinely not been told
// anything yet rather than having been told there is nothing.
//
// Pointers remain valid until `spotty_playback_free_queue_snapshot`.
SpottyNullableQueueSnapshot spotty_playback_get_queue_snapshot(void);

// Returns the sticky resume-load context URI (`CURRENT_CONTEXT_URI`), or null if none.
// The caller owns the returned string and frees it with `spotty_playback_free_string`.
// An empty string is a present empty value.
SpottyNullableMutCString spotty_playback_get_resume_context_uri(void);

// Returns the position saved at deactivation for a resume load, or 0 to use the live playhead.
uint32_t spotty_playback_get_resume_position_ms(void);

// Returns the sticky resume-load track URI (`CURRENT_TRACK_URI`), or null if none.
// The caller owns the returned string and frees it with `spotty_playback_free_string`.
// An empty string is a valid context hint.
SpottyNullableMutCString spotty_playback_get_resume_track_uri(void);

// Initializes the player.
// Must be called before play/pause operations.
//
// # Parameters
// - `access_token`: A token minted with librespot's client id, or null to connect from the
//   credentials cached by [`spotty_playback_authorize_streaming`]. Null is the normal case:
//   only the first init after a grant carries a token.
SpottyPlaybackResult spotty_playback_init_player(SpottyNullableCString access_token);

// Loads a context or single track at `position_ms`.
//
// `rehydrating_generation == 0` is a user-resume load: it waits briefly for a Playing event.
// A nonzero value names the engine session generation being rehydrated after a reconnect: the
// engine runs the load only if that generation is current and its `resume_pending` window is
// still open, and returns 0 as soon as the load is queued (the window is the only Playing wait).
// Otherwise it returns an ordinary failure without touching the session. Empty `track_hint` is
// a valid context hint; `uri` must be non-empty.
//
// # Parameters
// - `uri`: Context or track URI.
// - `track_hint`: Optional current-track hint for a context load.
// - `from_context`: True for a context URI, false for a single track URI.
SpottyPlaybackResult spotty_playback_load(const char *uri,
                                          SpottyNullableCString track_hint,
                                          uint32_t position_ms,
                                          bool from_context,
                                          uint64_t rehydrating_generation);

// Skips to the next track in the queue.
// Returns 0 on success, -1 on error, -2 if channel closed (needs reinit).
SpottyPlaybackResult spotty_playback_next(void);

// Pauses playback. A successful pause publishes the accepted local paused snapshot so Swift
// can stop display interpolation before the next player event.
SpottyPlaybackResult spotty_playback_pause(void);

// Plays multiple tracks in sequence.
//
// # Parameters
// - `track_uris_json`: JSON array of track URIs as a C string.
SpottyPlaybackResult spotty_playback_play_tracks(const char *track_uris_json);

// Plays content by its Spotify URI or URL.
// Supports albums, playlists, and artists (context URIs).
//
// # Parameters
// - `uri_or_url`: Spotify URI or URL (for example, "spotify:album:xxx").
SpottyPlaybackResult spotty_playback_play_uri(const char *uri_or_url);

// Skips to the previous track in the queue.
// Returns 0 on success, -1 on error, -2 if channel closed (needs reinit).
SpottyPlaybackResult spotty_playback_previous(void);

// Registers a callback for audio control events (start/stop/clear). Called from librespot's
// player thread. Events are 0 = stop, 1 = start/resume, and 2 = clear/flush.
void spotty_playback_register_audio_control_callback(AudioControlCallback callback);

// Registers a callback to receive raw PCM audio data (f32, 44100Hz, stereo interleaved).
// Called from librespot's player thread for each decoded audio chunk. The samples pointer is
// valid only for the callback invocation, and the callback must be thread-safe.
void spotty_playback_register_audio_data_callback(AudioDataCallback callback);

// Registers a callback to receive connection state change notifications.
// Called whenever the connection state changes (connect, disconnect, error, etc.).
// The callback receives a C snapshot; string pointers are valid only for the call.
void spotty_playback_register_connection_state_callback(ConnectionStateCallback callback);

// Registers a callback to receive the Connect device list from cluster updates.
// The callback receives a C snapshot; string pointers are valid only for the call.
// Fires only when the list actually changes, not on every cluster tick.
void spotty_playback_register_devices_callback(DevicesCallback callback);

// Registers a callback to receive playback state updates as a C snapshot.
// String pointers are valid only for the call.
void spotty_playback_register_playback_state_callback(PlaybackStateCallback callback);

// Registers a callback to receive queue updates as a C snapshot.
// String and nested pointers are valid only for the call.
void spotty_playback_register_queue_callback(QueueCallback callback);

// Resumes playback by activating the local device and issuing `play()`. If no Playing event
// arrives, Swift issues seek-capable load fallbacks through [`spotty_playback_load`]. Reconnect
// rehydration issues the same Swift targets while the connection snapshot reports
// `resume_pending`.
SpottyPlaybackResult spotty_playback_resume(void);

// Seeks to the given position in milliseconds.
// Returns 0 on success, -1 on error, -2 if channel closed (needs reinit).
SpottyPlaybackResult spotty_playback_seek(uint32_t position_ms);

// Sets the user-facing device name advertised to Spotify Connect. Must be called before
// `spotty_playback_init_player` to affect the next Spirc instance. The string is copied during
// this call.
void spotty_playback_set_device_name(const char *device_name);

// Repeats the current playback context (repeat the whole queue).
SpottyPlaybackResult spotty_playback_set_repeat_context(bool enabled);

// Repeats the current track (repeat one).
SpottyPlaybackResult spotty_playback_set_repeat_track(bool enabled);

// Sets shuffle mode for the current playback context.
SpottyPlaybackResult spotty_playback_set_shuffle(bool enabled);

// Shuts down the Spirc connection and sends goodbye to other devices.
// Call this when the app is quitting to properly disconnect from Spotify Connect.
// Returns 0 on success, -1 on error.
SpottyPlaybackResult spotty_playback_shutdown(void);

// Transfers playback from this local player to another device using the native Spotify Connect
// protocol via SpClient.
//
// # Parameters
// - `to_device_id`: The target device ID to transfer playback to.
SpottyPlaybackResult spotty_playback_transfer_playback(const char *to_device_id);

// Transfers playback from another device to this local player.
// Uses the native Spotify Connect protocol via Spirc.
// Returns 0 on success, -1 on error.
SpottyPlaybackResult spotty_playback_transfer_to_local(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#pragma clang assume_nonnull end
